# Generated by Django 4.2.2 on 2023-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingleave',
            name='leaves_taken',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
