# Generated by Django 4.2.2 on 2023-07-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_pendingleave_leaves_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
