# Generated by Django 4.2.2 on 2023-07-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='duration',
        ),
    ]
